/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignRouteImport } from './routes/design'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as MeRouteImport } from './routes/me'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DevSeedRouteImport } from './routes/dev.seed'
import { Route as DevWorkRouteImport } from './routes/dev.work'
import { Route as OauthAuthorizeRouteImport } from './routes/oauth/authorize'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner.$repo.index'
import { Route as OwnerRepoIssuesNumberRouteImport } from './routes/$owner.$repo.issues.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSeedRoute = DevSeedRouteImport.update({
  id: '/dev/seed',
  path: '/dev/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const DevWorkRoute = DevWorkRouteImport.update({
  id: '/dev/work',
  path: '/dev/work',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/$owner/$repo/',
  path: '/$owner/$repo/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIssuesNumberRoute = OwnerRepoIssuesNumberRouteImport.update({
  id: '/$owner/$repo/issues/$number',
  path: '/$owner/$repo/issues/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/healthz': typeof HealthzRoute
  '/me': typeof MeRoute
  '/projects': typeof ProjectsRoute
  '/sign-in': typeof SignInRoute
  '/dev/seed': typeof DevSeedRoute
  '/dev/work': typeof DevWorkRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/issues/$number': typeof OwnerRepoIssuesNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/healthz': typeof HealthzRoute
  '/me': typeof MeRoute
  '/projects': typeof ProjectsRoute
  '/sign-in': typeof SignInRoute
  '/dev/seed': typeof DevSeedRoute
  '/dev/work': typeof DevWorkRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/issues/$number': typeof OwnerRepoIssuesNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/healthz': typeof HealthzRoute
  '/me': typeof MeRoute
  '/projects': typeof ProjectsRoute
  '/sign-in': typeof SignInRoute
  '/dev/seed': typeof DevSeedRoute
  '/dev/work': typeof DevWorkRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/issues/$number': typeof OwnerRepoIssuesNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/healthz'
    | '/me'
    | '/projects'
    | '/sign-in'
    | '/dev/seed'
    | '/dev/work'
    | '/oauth/authorize'
    | '/$owner/$repo/'
    | '/$owner/$repo/issues/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/healthz'
    | '/me'
    | '/projects'
    | '/sign-in'
    | '/dev/seed'
    | '/dev/work'
    | '/oauth/authorize'
    | '/$owner/$repo'
    | '/$owner/$repo/issues/$number'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/healthz'
    | '/me'
    | '/projects'
    | '/sign-in'
    | '/dev/seed'
    | '/dev/work'
    | '/oauth/authorize'
    | '/$owner/$repo/'
    | '/$owner/$repo/issues/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  HealthzRoute: typeof HealthzRoute
  MeRoute: typeof MeRoute
  ProjectsRoute: typeof ProjectsRoute
  SignInRoute: typeof SignInRoute
  DevSeedRoute: typeof DevSeedRoute
  DevWorkRoute: typeof DevWorkRoute
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  OwnerRepoIssuesNumberRoute: typeof OwnerRepoIssuesNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/seed': {
      id: '/dev/seed'
      path: '/dev/seed'
      fullPath: '/dev/seed'
      preLoaderRoute: typeof DevSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/work': {
      id: '/dev/work'
      path: '/dev/work'
      fullPath: '/dev/work'
      preLoaderRoute: typeof DevWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/authorize': {
      id: '/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof OauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/issues/$number': {
      id: '/$owner/$repo/issues/$number'
      path: '/$owner/$repo/issues/$number'
      fullPath: '/$owner/$repo/issues/$number'
      preLoaderRoute: typeof OwnerRepoIssuesNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  HealthzRoute: HealthzRoute,
  MeRoute: MeRoute,
  ProjectsRoute: ProjectsRoute,
  SignInRoute: SignInRoute,
  DevSeedRoute: DevSeedRoute,
  DevWorkRoute: DevWorkRoute,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  OwnerRepoIssuesNumberRoute: OwnerRepoIssuesNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
